package tech.pegasys.era;

import org.web3j.crypto.Credentials;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.core.RemoteCall;
import tech.pegasys.era.internal.AutoGeneratedEra;

import java.math.BigInteger;


public class EthereumRegistrationAuthorityFactory {
    private Web3j web3j;
    private Credentials credentials;



    public EthereumRegistrationAuthorityFactory(Web3j web3j, Credentials credentials) {
        this.web3j = web3j;
        this.credentials = credentials;
    }

    public EthereumRegistrationAuthorityFactory(Web3j web3j) {
        this.web3j = web3j;
    }


    public EthereumRegistrationAuthority eraDeploy() {
        // TODO check credentials not null

        BigInteger gasPrice = null; //TODO
        BigInteger gasLimit = null; // TODO
        RemoteCall<AutoGeneratedEra> result = AutoGeneratedEra.deploy(this.web3j, this.credentials, gasPrice, gasLimit);
        return new EthereumRegistrationAuthority(result);
    }

    // params: ethereum address
    public EthereumRegistrationAuthority eraAtAddress(String contractAddress) {
        return null;
    }


    public void deployDomainInfo() {

    }

    public void deployFinder() {

    }





}
