package tech.pegasys.era;

import org.web3j.protocol.core.RemoteCall;
import org.web3j.protocol.core.methods.response.TransactionReceipt;
import tech.pegasys.era.internal.AutoGeneratedEra;

import java.math.BigInteger;

public class EthereumRegistrationAuthority {

    RemoteCall<AutoGeneratedEra> eraAutoGenWrapper;
    AutoGeneratedEra eraAutoGenWrapperReal;

    // params: Web3j instance and a wallet
    public EthereumRegistrationAuthority(RemoteCall<AutoGeneratedEra> eraAutoGenWrapper) {
        this.eraAutoGenWrapper = eraAutoGenWrapper;
    }

    public boolean isReady() {
        return true;
    }

    public void waitUntilRead() {
        // TODO block until ready
        // convert from RemoteCall to concrete class ???
    }


    public RemoteCall<TransactionReceipt> addDomain(String domainName, String domainAuthorityContractAddress, String domainInfoContractAddress, String domainOwnerAddress) {
        // TODO convert from domainName to domainHash
        BigInteger domainHash = null;
        return this.eraAutoGenWrapperReal.addUpdateDomain(domainHash, domainAuthorityContractAddress, domainInfoContractAddress, domainOwnerAddress);
    }

    public void updateDomain() {

    }

}
